#!/bin/bash

# Need files generated by templated docker builder. Not easily available until ngc is built
# with rapidsdevtool.sh
# As a war cd to existing build-... directory and mount it by passing:
# docker run -w $PWD -v $PWD:$PWD ...
# Script below copies the files, clones notebooks and runs tests

cp -r . "$RAPIDS_DIR/"
cd "${RAPIDS_DIR}" || exit
./clone.sh notebooks
./test.sh

